name: Streamlit Deploy

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ Linux environment (default for GitHub Actions)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify chatbot.py exists
        run: |
          if [ ! -f "chatbot.py" ]; then
            echo "❌ chatbot.py not found!"
            exit 1
          fi

      - name: Deployment handled by Streamlit Cloud
        run: echo "🎉 Push complete. Streamlit Cloud will auto-deploy chatbot.py."
